Updating Lunexa

diff --git a/contrib/guix/guix-attest b/contrib/guix/guix-attest
--- a/contrib/guix/guix-attest
+++ b/contrib/guix/guix-attest
@@ -18,7 +18,7 @@ source "$(dirname "${BASH_SOURCE[0]}")/libexec/prelude.bash"
 # Required non-builtin commands should be invokable
 ################
 
-check_tools cat env basename mkdir diff sort
+check_tools cat env basename mkdir diff sort xargs tee
 
 if [ -z "$NO_SIGN" ]; then
     # make it possible to override the gpg binary
@@ -103,38 +103,6 @@ if [ -z "$NO_SIGN" ] && ! ${GPG} --dry-run --list-secret-keys "${gpg_key_name}" 
     exit 1
 fi
 
-################
-# We should be able to find at least one output
-################
-
-echo "Looking for build output SHA256SUMS fragments in ${LOGDIR_BASE}"
-
-shopt -s nullglob
-sha256sum_fragments=( "$LOGDIR_BASE"/*/SHA256SUMS.part ) # This expands to an array of directories...
-shopt -u nullglob
-
-noncodesigned_fragments=()
-codesigned_fragments=()
-
-if (( ${#sha256sum_fragments[@]} )); then
-    echo "Found build output SHA256SUMS fragments:"
-    for logdir in "${sha256sum_fragments[@]}"; do
-        echo "    '$logdir'"
-        case "$logdir" in
-            "$LOGDIR_BASE"/*-codesigned/SHA256SUMS.part)
-                codesigned_fragments+=("$logdir")
-                ;;
-            *)
-                noncodesigned_fragments+=("$logdir")
-                ;;
-        esac
-    done
-    echo
-else
-    echo "ERR: Could not find any build output SHA256SUMS fragments in ${LOGDIR_BASE}"
-    exit 1
-fi
-
 ##############
 ##  Attest  ##
 ##############
@@ -168,7 +136,6 @@ EOF
 }
 
 echo "Attesting to build outputs for version: '${VERSION}'"
-echo ""
 
 # Given a SHA256SUMS file as stdin that has lines like:
 #     0ba536819b221a91d3d42e978be016aac918f40984754d74058aa0c921cd3ea6  a/b/d/c/d/s/lunexa-aarch64-apple-darwin-v0.18.3.2.tar.bz2
@@ -187,77 +154,44 @@ mkdir -p "$outsigdir"
 (
     cd "$outsigdir"
 
-    temp_noncodesigned="$(mktemp)"
-    trap 'rm -rf -- "$temp_noncodesigned"' EXIT
-
-    if (( ${#noncodesigned_fragments[@]} )); then
-        cat "${noncodesigned_fragments[@]}" \
-            | sort -u \
-            | basenameify_SHA256SUMS \
-            | sort -k2 \
-                > "$temp_noncodesigned"
-        if [ -e noncodesigned.SHA256SUMS ]; then
-            # The SHA256SUMS already exists, make sure it's exactly what we
-            # expect, error out if not
-            if diff -u noncodesigned.SHA256SUMS "$temp_noncodesigned"; then
-                echo "A noncodesigned.SHA256SUMS file already exists for '${VERSION}' and is up-to-date."
-            else
-                shasum_already_exists noncodesigned.SHA256SUMS
-                exit 1
-            fi
-        else
-            mv "$temp_noncodesigned" noncodesigned.SHA256SUMS
-        fi
-    else
-        echo "ERR: No noncodesigned outputs found for '${VERSION}', exiting..."
-        exit 1
-    fi
-
     temp_all="$(mktemp)"
     trap 'rm -rf -- "$temp_all"' EXIT
 
-    if (( ${#codesigned_fragments[@]} )); then
-        # Note: all.SHA256SUMS attests to all of $sha256sum_fragments, but is
-        #       not needed if there are no $codesigned_fragments
-        cat "${sha256sum_fragments[@]}" \
-            | sort -u \
-            | sort -k2 \
-            | basenameify_SHA256SUMS \
-                > "$temp_all"
-        if [ -e all.SHA256SUMS ]; then
-            # The SHA256SUMS already exists, make sure it's exactly what we
-            # expect, error out if not
-            if diff -u all.SHA256SUMS "$temp_all"; then
-                echo "An all.SHA256SUMS file already exists for '${VERSION}' and is up-to-date."
-            else
-                shasum_already_exists all.SHA256SUMS
-                exit 1
-            fi
+    echo "Looking for build output SHA256SUMS fragments in ${LOGDIR_BASE}"
+    all_fragments=$(find "$LOGDIR_BASE" -name "SHA256SUMS.part" -print0 | xargs -0 sort -u /dev/null | basenameify_SHA256SUMS | sort -k2 | tee "$temp_all")
+
+    if [ -z "${all_fragments}" ]; then
+        echo "ERR: Could not find any build output SHA256SUMS fragments in ${LOGDIR_BASE}"
+        exit 1
+    fi
+
+    all_file="all.SHA256SUMS"
+    if [ -e "$all_file" ]; then
+        # The SHA256SUMS already exists, make sure it's exactly what we
+        # expect, error out if not
+        if diff -u ${all_file} "$temp_all"; then
+            echo "A ${all_file} file already exists for '${VERSION}' and is up-to-date."
         else
-            mv "$temp_all" all.SHA256SUMS
+            shasum_already_exists "$all_file"
+            exit 1
         fi
     else
-        # It is fine to have the codesigned outputs be missing (perhaps the
-        # detached codesigs have not been published yet), just print a log
-        # message instead of erroring out
-        echo "INFO: No codesigned outputs found for '${VERSION}', skipping..."
+        mv "$temp_all" "$all_file"
     fi
 
     if [ -z "$NO_SIGN" ]; then
-        echo "Signing SHA256SUMS to produce SHA256SUMS.asc"
-        for i in *.SHA256SUMS; do
-            if [ ! -e "$i".asc ]; then
-                ${GPG} --detach-sign \
-                       --digest-algo sha256 \
-                       --local-user "$gpg_key_name" \
-                       --armor \
-                       --output "$i".asc "$i"
-            else
-                echo "Signature already there"
-            fi
-        done
+        echo "Signing ${all_file} to produce ${all_file}.asc"
+
+        if [ ! -e "$all_file".asc ]; then
+            ${GPG} --detach-sign \
+                   --digest-algo sha256 \
+                   --local-user "$gpg_key_name" \
+                   --armor \
+                   --output "$all_file".asc "$all_file"
+        else
+            echo "Signature already there"
+        fi
     else
-        echo "Not signing SHA256SUMS as \$NO_SIGN is not empty"
+        echo "Not signing ${all_file} as \$NO_SIGN is not empty"
     fi
-    echo ""
 )
